server:
  port: 7000

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


