server:
  port: 13000

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.82.2:3306/mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-coupons
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.82.2:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


