spring:
  cloud:
    alicloud:
      access-key: LTAI5tCj8W6eus9GtTXajiaT
      secret-key: KJ8oWkIy8ausWp5CTC8zYMgoSBKRFm
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: zengjianhong-bucket
server:
  port: 9999
